on:
    push:
      branches:
        - master
name: release-please
jobs:
    release-please:
      runs-on: ubuntu-latest
      outputs:
        releases_created: ${{ steps.release-please.outputs.releases_created }}
      steps:
        - id: release-please
          uses: google-github-actions/release-please-action@v3
          with:
            release-type: node
            package-name: release-please-action
    deploy:
      uses: gr8fit-tech/flutterwave-react-native/.github/workflows/master.yaml@master
      needs: [release-please]
      if: ${{ needs.release-please.outputs.releases_created }}
      secrets: inherit
  